#!/bin/bash
#
# GlassFish v3 ClickStack plugin for CloudBees PaaS
#
# setup script is called by when a Java web app is deployed with GlassFish v3
# as target application server.

set -u
set -e

. "$plugin_dir/functions"

install_app
write_config
write_jvm_opts
write_system_props
write_control
