#!/bin/bash
set -e
set -u
control_dir="$(dirname $0)"
. "$control_dir/java/functions"
. "$control_dir/config"
. "$control_dir/env_safe"

java_opts="$(java_opts $control_dir)"

exec bash -c "
$java \
  $java_opts \
  -Dapp_port=$port \
  -Djava.io.tmpdir=\"$app_tmp\" \
  -jar $glassfish_base/modules/glassfish.jar
"
