#!/bin/sh
set -e
set -u

control_dir="$(dirname $0)"
. $control_dir/config

# GlasFish main class
glassfish_bootstrap_jar=$glassfish_base/modules/glassfish.jar


# Collect all the java_opts
java_opts=""
for f in `ls $control_dir/java-opts-* | sort`; do
    java_opts="$java_opts `cat $f`"
done

# Execute GlassFish v3
exec $java \
    -Dapp_port=$port \
    $java_opts \
    -jar $glassfish_bootstrap_jar

